CREATE TABLE `m_feedback` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `text_id` varchar(255) DEFAULT NULL,
  `short_title` varchar(255) DEFAULT NULL,
  `long_title` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date_time` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date_time` datetime DEFAULT NULL,
  `system_update_count` int(11) DEFAULT NULL,
  `system_delete_flag` bit(1) DEFAULT NULL,
  `created_program` varchar(255) DEFAULT NULL,
  `created_user` varchar(255) DEFAULT NULL,
  `system_created_date_time` datetime DEFAULT NULL,
  `system_updated_date_time` datetime DEFAULT NULL,
  `updated_program` varchar(255) DEFAULT NULL,
  `updated_user` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_feedback` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `rating` int(11) DEFAULT NULL,
  `feedback_master_id` bigint(20) DEFAULT NULL,
  `seekers_feedback_id` bigint(20) DEFAULT NULL,
  `taskers_feedback_id` bigint(20) DEFAULT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date_time` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date_time` datetime DEFAULT NULL,
  `system_update_count` int(11) DEFAULT NULL,
  `system_delete_flag` bit(1) DEFAULT NULL,
  `created_program` varchar(255) DEFAULT NULL,
  `created_user` varchar(255) DEFAULT NULL,
  `system_created_date_time` datetime DEFAULT NULL,
  `system_updated_date_time` datetime DEFAULT NULL,
  `updated_program` varchar(255) DEFAULT NULL,
  `updated_user` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_seekers_feedback` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` varchar(255) DEFAULT NULL,
  `task_code` varchar(255) DEFAULT NULL,
  `task_title` varchar(255) DEFAULT NULL,
  `category_id` varchar(255) DEFAULT NULL,
  `category_code` varchar(255) DEFAULT NULL,
  `category_title` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `user_email` varchar(255) DEFAULT NULL,
  `user_short_name` varchar(255) DEFAULT NULL,
  `user_long_name` varchar(255) DEFAULT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date_time` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date_time` datetime DEFAULT NULL,
  `system_update_count` int(11) DEFAULT NULL,
  `system_delete_flag` bit(1) DEFAULT NULL,
  `created_program` varchar(255) DEFAULT NULL,
  `created_user` varchar(255) DEFAULT NULL,
  `system_created_date_time` datetime DEFAULT NULL,
  `system_updated_date_time` datetime DEFAULT NULL,
  `updated_program` varchar(255) DEFAULT NULL,
  `updated_user` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_taskers_feedback` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` varchar(255) DEFAULT NULL,
  `task_code` varchar(255) DEFAULT NULL,
  `task_title` varchar(255) DEFAULT NULL,
  `category_id` varchar(255) DEFAULT NULL,
  `category_code` varchar(255) DEFAULT NULL,
  `category_title` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `user_email` varchar(255) DEFAULT NULL,
  `user_short_name` varchar(255) DEFAULT NULL,
  `user_long_name` varchar(255) DEFAULT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date_time` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date_time` datetime DEFAULT NULL,
  `system_update_count` int(11) DEFAULT NULL,
  `system_delete_flag` bit(1) DEFAULT NULL,
  `created_program` varchar(255) DEFAULT NULL,
  `created_user` varchar(255) DEFAULT NULL,
  `system_created_date_time` datetime DEFAULT NULL,
  `system_updated_date_time` datetime DEFAULT NULL,
  `updated_program` varchar(255) DEFAULT NULL,
  `updated_user` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



